### ISSUE TITLE
[Proposal] Sync master instead of multi - master

### ISSUE THREAD

**Issue by lantisnt** [Slivo-fr/TranqRotate#11]
Hi mate, looking into your addon and waiting for it to be done. It is very promising. 
I see you are struggling with the Syncing. Issue is that by default outside of guild this may be an multi master system. Have you thought about reworking it into Single master? This can be achieved easily by multiple means. Simplest would be to set master to first hunter in the raid with addon installed. Every other hunter would  then be a Slave in this system. If the master woudl quit raid the master would be given to next on list. Other option is that if RL/assist has the addon installed would be the sync master by default.

**Comment by Slivo-fr** [comment]
Hey, thanks :)

The addon itself is working pretty well already with the minors inconvenient that your hunters must stay at range and each one has to configure the rotation ! I'm using it in raids for a while now.

I'm not really struggling with sync, it's almost done. I'm going to test an alpha out of raid in the next days and release a beta if everything is fine to be able to test it in raid conditions.

I have some kind of master / slave plan in my head that will be paired with RL/assist roles, but It will come in a second step. I want  to release a peer to peer working sync for rotation and tranqshot as soon as possible. 

Thanks for your interest in the project, you may watch how it's going on the dedicated branch there : https://github.com/Slivo-fr/TranqRotate/tree/feature/sync

**Comment by Slivo-fr** [comment]
First beta out, feel free to try it on magmadar :P

**Comment by lantisnt** [comment]
Thx, were going to test it today in BWL :)

**Comment by Slivo-fr** [comment]
I would not advice to test that on BWL yet as fight are a bit more critic.

It should however work fine, I had the beta yesterday on BWL as backup and had no issue (but was alone with the beta at the time). 

We are going to test it live in MC with a full raid with beta on sunday.
