### ISSUE TITLE
TranqShot interfering with dialog boxes

### ISSUE THREAD

**Issue by lantisnt** [Slivo-fr/TranqRotate#13]
**Version** : v1.2.0 - beta

**Description**

With AddOn enabled - in party - outside of raid, outside of instance (Ironforge), when I was trying to apply Accurascope to bow with damage enchant the dialog box that popped for confirming was closed after 1 - 3s each time (with no reenchant - thus assuming cancel). This stopped when i disabled TranqShot. Probably some events / communication actions are interfering with popups. 
This happened using default UI.

**Steps to reproduce**

- Enable addon
- Try doing action that requires a popup (e.g. reenchant an item)
- Wait 1 - 3 s

**Additional information**

Occured to me when applying Accurascope

**Comment by Slivo-fr** [comment]
Hello ! 

Thanks for testing and reporting this issue, I will try to reproduce it on my side later today.

Few questions :
- Could you retry with only TranqRotate enabled and confirm it still happens ?
- If so, could you please try with v1.1.0 see if that's a v1.2.0 issue ?
- Does it happens with cheaper items ? I don't have any accurascope and would like to avoid buying one xP

Congratulation for your crossbow I guess :D

**Comment by Slivo-fr** [comment]
Just tried it with a lower end scope, I can reproduce your issue.
It however happens even if I have no addon installed at all.
Could you please check if it still happens when you disable all addons ?

**Comment by lantisnt** [comment]
Could you clarify no addon at all? - Does this mean also no TranqRotate?

**Comment by Slivo-fr** [comment]
Yup, none at all. TranqRotate disabled too

**Comment by lantisnt** [comment]
Oh ok. I was not able to reproduce it today. Classic Bug report?

**Comment by Slivo-fr** [comment]
Look like it yeah xP
Thanks for reporting anyway, I'll keep this open until release just in case

**Comment by lantisnt** [comment]
not addon bug:
https://eu.forums.blizzard.com/en/wow/t/bug-report-enchancement-scope-replacement-dialog-auto-closing/129665

**Comment by Slivo-fr** [comment]
Thanks for finding out the problem :)
