### ISSUE TITLE
[Feature request] Internal "Tranq now" announce

### ISSUE THREAD

**Issue by lantisnt** [Slivo-fr/TranqRotate#15]
Instead of whisper an internal message should be sent to next person in rotation AND all backups that they should tranq on tranq fail.

This should result in prompt in the middle of screen (DBM-like).
This is achievable through raid warning but shows to all players instead of hunters.

**Comment by Slivo-fr** [comment]
Hey,

Thanks for your involvment !

I'm planning to add internal raid-warning or DBM-like prompt at some point already.
I however want this addon to be effective even if you are the only hunter with the addon in the raid, whisper are necessary. I will try to only whisper hunters without the addon once everything is ready but that's still far ahead.

**Comment by Slivo-fr** [comment]
This feature is going to be part of the 1.4 release :)

**Comment by Slivo-fr** [comment]
Added in v1.4.0 ! Please report any issue !
