### ISSUE TITLE
[Feature request] Timed notification of backup / next hunter

### ISSUE THREAD

**Issue by lantisnt** [Slivo-fr/TranqRotate#17]
After N (configurable) seconds of target getting in frenzy and not receiving tranq next person in rotation and all backups should be notified to tranq.

**Comment by Slivo-fr** [comment]
Hey,

Great idea ! I'm however unable to know frenzy status and start at the moment, I'll check how I can put your idea in place once frenzy is handled :)

**Comment by cltnschlosser** [comment]
I use a weak aura for when to tranq that checks that the target has a buff called `Frenzy`. 

Looks like these are all the matching IDs
![image](https://user-images.githubusercontent.com/1498529/91078524-6103fe80-e608-11ea-8233-d37020b0f412.png)

Hopefully this helps.

**Comment by Slivo-fr** [comment]
Hey @cltnschlosser !

Thanks for the data, however I did look them up myself last week as I was working on the "tranq now" alert feature :D
This feature request should be in the top 3 next I will (try to) add !

I'm a bit unsure about the configurable delay as it could cause some weird behavior if people in the same raid use a different value. Exemple, Hunter A from rotation group is too far away/Stun and has set a 3 seconds delay, Hunt B from backup has set 1s before alert : Hunter B will receive backup call from A 2 seconds after it's own TranqRotate asked him to shoot). I may start with a fixed value of say ... 2s maybe ?

**Comment by Slivo-fr** [comment]
Forgot to close this, it's part of the 1.5.0 release ! :)
