### ISSUE TITLE
Chinese character in player names aren't displayed properly

### ISSUE THREAD

**Issue by DarkPisCeS03** [Slivo-fr/TranqRotate#24]
**Version** : 1.13.3

**Description**

This is a good addon, but the name tab to change the position, it can't display Chinese characters, only quest marks.

**Steps to reproduce**

when joining to RAID, the name tab only shows the question marks

**Comment by Slivo-fr** [comment]
Hey there,

Thanks for your feedback !
That's not something I can test on my side unfortunately, It should be working as I'm getting the name from the game itself.

I'll try to dig into that see if I can find a fix

**Comment by DarkPisCeS03** [comment]
Hi Silvo,

Thanks for your prompt reply, just wondering if there is somewhere to set the font? it might be font issue.

thanks.

**Comment by DarkPisCeS03** [comment]
Hey Silvo, 
We found the location to replace font and it works fine.
"TranqRotate\src\frames.lua"
"Fonts\ARIALN.ttf" =>"Fonts\ARHei.ttf"
Thanks a lot.

**Comment by Slivo-fr** [comment]
Yeah I was looking at the font, I've been advised to !
I will try to change the font or make it language specific in the next release. 

Thanks for reporting !

**Comment by Slivo-fr** [comment]
Could you please tell me which locales are affected ?

**Comment by DarkPisCeS03** [comment]
Hi Slivo-fr, it's in zhTW.lua

**Comment by LeePich** [comment]
Yes, it's always been a problem,
ZhCN/zhTW will be affected.

In version 1.3.0, you would simply replace line 154 of "TranqRotate\src\frames.lua"
`    hunter.frame.text:SetFont("Fonts\\ARIALN.ttf", 12)`
"Fonts\\ARIALN.ttf" =>"Fonts\\ARHei.ttf"

**Comment by Slivo-fr** [comment]
I wanted to do this at first, but the font is a bit different ... I could use this font only for affected locales or find another one. I'll work on this for 1.3.0

**Comment by Slivo-fr** [comment]
This issue should be solved by v1.3.0-beta2 (soon) available on curse or there https://github.com/Slivo-fr/TranqRotate/releases/tag/v1.3.0-beta2
Please give it a try and keep me updated :)

**Comment by LeePich** [comment]
It worked

**Comment by Slivo-fr** [comment]
Solved, available in the 1.3.0 release :)
