### ISSUE TITLE
[Feature Request] Default window to hidden for non hunters

### ISSUE THREAD

**Issue by cltnschlosser** [Slivo-fr/TranqRotate#36]
Would be nice to not have to close the window everytime I log in on a different class.

**Comment by Slivo-fr** [comment]
Hey,

The next release will ship several options that will help with this , on
hunters and non hunters characters.

I don't want to change the behavior for non hunter as this add-on works for
non-hunters raid leaders.

Meanwhile wow does allow you to manage per character add-on settings

**Comment by cltnschlosser** [comment]
> Meanwhile wow does allow you to manage per character add-on settings

I didn't know this, but this is exactly what I wanted, so going to close this :)
