### ISSUE TITLE
1.7.0 Translations

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/TranqRotate#47]
There are some new strings in the `1.7.0-beta1` build !
If you guys are still around, please opens MRs to the `release/v1.7.0` branch

@LeePich @T3rdW @ivan-rabtsevich @FenixsRU 

Thanks !

**Comment by FenixsRU** [comment]
Done

**Comment by Slivo-fr** [comment]
Thanks Fenixs !
